# Generated by Django 3.0.6 on 2020-05-20 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20200519_1132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
